name:    yesod-minimal
version: "0.0.0"

dependencies:
- base
- yesod-core

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  dependencies:
  - wai
  - blaze-builder
  - http-types
  - bytestring
  - text
  - aeson

# Runnable executable for our application
executables:
  yesod-minimal:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-minimal
